packages/api/prisma/migrations/20240617131510_test_news_community/migration.sql, packages/api/src/ebsco/search/abstractSearch.service.ts, packages/api/src/ebsco/searchAlert/searchAlert.controller.spec.ts, packages/api/src/ebsco/searchAlert/searchAlert.service.ts, packages/api/src/ebsco/searchAlert/searchAlert.utils.ts, packages/api/src/ebsco/searchAlert/searchAlertCron.service.ts
Fix(searchAlert): Add last_results when creating alert
=> Fix(searchAlert): Remove parallelism as it was causing ebsco error

packages/e2e/tests/navigation.spec.ts, packages/front/src/app/pages/search/database/Database.tsx
=> Fix Platform search button

packages/e2e/tests/favorites.spec.ts, packages/front/src/app/pages/user/favourite/FavouriteList.tsx, packages/front/src/app/pages/user/favourite/FavouriteListItem.tsx, packages/front/src/app/shared/locales/I18N.ts, packages/front/src/app/shared/locales/common/en.ts, packages/front/src/app/shared/locales/common/fr.ts
Fix and imporve drag n drop of favourite:
- Add a drag handler
- Disable layoutchange animation 
- be optimistic when reordering favourites
- update tests
=> Fix dragndrop

packages/e2e/tests/advanced-search.spec.ts, packages/front/src/app/context/themes/dark.tsx, packages/front/src/app/pages/search/article/ArticleAdvancedSearchGroup.tsx, packages/front/src/app/pages/search/article/ArticleAdvancedSearchItem.tsx, packages/front/src/app/pages/search/article/ArticlePage.tsx, packages/front/src/app/shared/locales/I18N.ts, packages/front/src/app/shared/locales/common/en.ts, packages/front/src/app/shared/locales/common/fr.ts
The advanced search button was too discreet
Add text to the icon to make it more visible
Also imporved selecto on advanced search test that were too brittle
Go to Article page
=> Better advanced search button

packages/front/src/app/components/page/render/RenderNews.tsx, packages/front/src/app/context/themes/dark.tsx, packages/front/src/app/context/themes/light.tsx
Chip are too small
Test news are not emphasized enough
Make the font bigger (it was already in bold)
On test  news change the background to yellow
=> augment fontSize for all Chip

packages/front/src/app/pages/search/publication/PublicationTitle.tsx
=> Fix(publication): Add OA logo when publication is diamond and user is logged in

packages/front/src/app/components/element/button/BookmarkButton.tsx
https://github.com/user-attachments/assets/d4a932d1-e87c-4bac-9ce5-a0263a75f0ab
=> Fix(bookmark): Remove bookmark button if user is not janus

packages/front/src/app/pages/search/publication/PublicationCard.tsx, packages/front/src/app/pages/search/publication/PublicationSidebar.tsx, packages/front/src/app/pages/search/publication/prioritizeLinks.ts, packages/front/src/app/pages/search/publication/prioritizeLinksCommons.spec.ts, packages/front/src/app/pages/search/publication/prioritizeLinksCommons.testdata.ts, packages/front/src/app/pages/search/publication/prioritizeLinksCommons.ts, packages/front/src/app/pages/search/publication/prioritizeLinksV1.spec.ts, packages/front/src/app/pages/search/publication/prioritizeLinksV1.ts, packages/front/src/app/pages/search/publication/prioritizeLinksV2.spec.ts, packages/front/src/app/pages/search/publication/prioritizeLinksV2.ts
Current link priorization algorithm is too complex
Implement and easier algorithm
=> Feat(publication): Add support for simplify link algorithm

packages/front/src/app/pages/search/database/PlatformListView.tsx
https://github.com/user-attachments/assets/32a4eb0c-b7cf-426c-8b33-1ec91f45ed30
=> Fix(platform): OA and embargo icons are now displayed as expected for list view

packages/e2e/tests/home.spec.ts, packages/front/src/app/pages/Root.tsx
=> Feat(home): Add domains to search bar when logged in as a janus user

packages/api/package.json, packages/api/src/common/logger/AbstractLogger.ts, packages/api/src/common/logger/AppLogger.ts, packages/api/src/common/logger/FileLogger.ts, packages/api/src/ebsco/oa/oa.controller.ts, packages/api/src/ebsco/search/abstractSearch.service.ts, packages/api/src/ebsco/searchAlert/searchAlertCron.service.ts, yarn.lock
System ops have to stop and start services every day to retirve logs and rotate them
Implement rotating logs
=> Feat(ops): Add rotating log support

docker-compose.dev.yml, docker-compose.prod.yml, packages/api/src/config.ts, packages/api/src/ebsco/searchAlert/searchAlertCron.service.ts
=> Feat(searchAlert): Add link to manage search alerts at the bottom of the mail

packages/front/src/app/components/page/header/components/LocaleButton.tsx
=> Fix(header): Update language icon

packages/front/src/app/components/element/table/TableHistory.tsx
=> Fix(history): Update button colors

packages/front/src/app/pages/user/favourite/FavouriteListItem.tsx
=> fix favorites number of lines

packages/front/src/app/pages/user/history/History.tsx
=> Fix(searchAlert): Update delete button style

docker-compose.prod.yml
make search alerte failed
shibb config pb
fix container name
remove var proxy in shibb container
=> fix compose

packages/api/src/ezticket/ezticket.controller.ts
param gate in url redirect by api ezticket
=> fix param gate in redirect ezticket

.vscode/settings.json, packages/front/src/app/pages/search/database/PlatformCardView.tsx, packages/front/src/app/pages/search/database/PlatformPage.tsx, packages/front/src/app/shared/locales/I18N.ts, packages/front/src/app/shared/locales/common/en.ts, packages/front/src/app/shared/locales/common/fr.ts
BUG pagination page plateformes, passage de pages + error TODO dans usePlatform
=> fix-page-KB:11942

.vscode/settings.json, packages/front/src/app/components/page/search/FacetSidebar.tsx, packages/front/src/app/components/page/search/facet/FacetList.tsx, packages/front/src/app/components/page/search/facet/FacetSearchList.tsx, packages/front/src/app/pages/search/article/ArticlePage.tsx, packages/front/src/app/pages/search/database/PlatformCardView.tsx, packages/front/src/app/pages/search/database/PlatformPage.tsx, packages/front/src/app/pages/search/publication/PublicationPage.tsx, packages/front/src/app/services/search/Publication.ts, packages/front/src/app/shared/locales/I18N.ts, packages/front/src/app/shared/locales/common/en.ts, packages/front/src/app/shared/locales/common/fr.ts
filtres publications
J'ai accompli la tâche, mais le code n'est pas propre, donc c'est temporaire.
=> Fix filter publication

packages/api/src/ezticket/ezticket.controller.ts
route login in not connected mode never called
=> fix: ezticket route refactor

packages/admin/src/dataProvider.ts, packages/admin/src/i18n/fr.ts, packages/admin/src/licenses/LicenseCreate.tsx, packages/admin/src/licenses/LicenseEdit.tsx, packages/admin/src/licenses/LicenseList.tsx, packages/admin/src/resources/ResourcesForm.tsx, packages/api/prisma/migrations/20241104072055_licences_add_media_id/migration.sql, packages/api/prisma/migrations/20241105095255_drop_column_pdf_license/migration.sql, packages/api/prisma/migrations/20241112073045_add_media_and_drop_href_resources/migration.sql, packages/api/prisma/schema.prisma, packages/api/src/admin/licenses/dto/license.dto.ts, packages/api/src/admin/licenses/licenses.controller.spec.ts, packages/api/src/admin/licenses/licenses.service.ts, packages/api/src/admin/resources/dto/resource.dto.ts, packages/api/src/admin/resources/resources.controller.spec.ts, packages/api/src/admin/resources/resources.service.ts, packages/api/src/front/license/license.service.ts, packages/api/src/front/resource/resource.controller.spec.ts, packages/api/src/front/resource/resource.service.ts, packages/api/test/seed-e2e.ts, packages/api/test/seed.ts, packages/e2e/tests/resources.spec.ts, packages/front/src/app/pages/common/resources/Resources.tsx, packages/front/src/app/pages/user/licences/Licences.tsx, packages/front/src/app/services/user/Licences.ts, packages/front/src/app/shared/types/data.types.ts
ajout de media pour ressources et licences 
KB:11832
kb:11598
kb:12180
=> Fix bibadmin media

packages/admin/src/licenses/LicenseCreate.tsx, packages/admin/src/licenses/LicenseEdit.tsx, packages/admin/src/resources/ResourcesForm.tsx, packages/admin/src/testsNews/TestNewsForm.tsx
=> fix-KB:12200

packages/e2e/tests/advanced-search.spec.ts, packages/front/src/app/context/AdvancedSearchContext.tsx
=> fix-KB:12061

packages/admin/src/dataProvider.ts, packages/admin/src/medias/MediasCreate.tsx, packages/api/src/admin/medias/medias.controller.spec.ts, packages/api/src/admin/medias/medias.controller.ts, packages/api/src/admin/medias/medias.service.ts, packages/api/src/front/resource/resource.service.ts, packages/front/src/app/pages/common/resources/Resources.tsx
=> Fix lodex resources

packages/front/src/app/components/page/searchbar/SearchBar.spec.tsx, packages/front/src/app/components/page/searchbar/SearchBar.tsx, packages/front/src/app/pages/Root.tsx, packages/front/src/app/pages/search/article/ArticlePage.tsx, packages/front/src/app/pages/search/database/PlatformPage.tsx, packages/front/src/app/pages/search/metadore/MetadorePage.tsx, packages/front/src/app/pages/search/publication/PublicationPage.tsx, packages/front/src/app/pages/user/favourite/Favourite.tsx, packages/front/src/app/pages/user/favourite/FavouriteListItem.tsx, packages/front/src/app/pages/user/history/History.tsx
=> Fix search plateform

packages/admin/src/units/UnitsList.tsx, packages/front/src/app/components/page/home/FavouriteCardHome.tsx
fix KB des comptes Janus et Inist sur bibadmin+ Re fix KB couleur favoris épinglé  miss couleur jaune dans la homePage
=> fix-KB:12221

packages/admin/src/databases/DatabasesList.tsx, packages/admin/src/i18n/fr.ts, packages/api/src/admin/databases/databases.service.ts
=> fix-KB:12243

packages/api/Dockerfile
=> fix(api): upgrading docker node version

docker-compose.int.yml, docker-compose.prod.yml, packages/api/src/front/database/database.controller.spec.ts, packages/api/src/front/database/database.controller.ts, packages/api/src/front/database/database.service.ts, packages/e2e/tests/cms.spec.ts, packages/front/package.json, packages/front/src/app/App.tsx, packages/front/src/app/components/page/searchbar/SearchBar.tsx, packages/front/src/app/shared/locales/I18N.ts, packages/front/src/app/shared/locales/common/en.ts, packages/front/src/app/shared/locales/common/fr.ts, packages/front/src/app/shared/matomo.tsx, yarn.lock
=> fix KB-12234

packages/front/src/app/components/page/footer/Footer.tsx
=> fix(logos) final
